### PR TITLE
Update gedcom.md

### PR DESCRIPTION
**Pull request by hartenthaler**
updated based on https://en.wikipedia.org/wiki/GEDCOM

There are two revisions of GEDCOM-L standard (which could be transferred into two lines)

### CODE REVIEW

**Comment by fisharebest** [comment]
I originally included 7.0.0-rc1 (and other rc releases).

At the request of the GEDCOM 7 standards committee, I removed all references to it.

**Comment by hartenthaler** [comment]
... whatever happened at that time, they do not like that there is any information on the internet available about it. But in Wikipedia, the rc and the comment about it are still visible.

**Comment by fisharebest** [comment]
> But in Wikipedia, the rc and the comment about it are still visible.

True.

But the GEDCOM committee asked me to remove the links, and I did.

Similar to the remove of Tamura's specification.

**Comment by fisharebest** [comment]
The date for the 5.2 draft is earlier than the date for the 5.1 draft.
I have also seen this date somewhere.  But 1993 would make more sense than 1992.

Is there a PDF or other copy of the GEDCOM-L R1 spec?  It would be good to include both.

> There are two revisions of GEDCOM-L standard (which could be transferred into two lines)

I agree it would be good to have two lines, with two dates/versions.

**Pull request merged**
