### PR TITLE
Add 1.7-2.0 upgrade steps

### PR DESCRIPTION
**Pull request by jchue**
Just a quick addition to the upgrade documentation that I think a lot of people are looking for. I also updated the heading numbering. The sizing doesn't look too good right now, but I'd like to follow-up with some template updates later.

### CODE REVIEW

**Comment by jchue** [comment]
Oh and by the way, thank you for all your hard work on 2.0. Upgrading was pretty seamless for me, and I have yet to encounter an issue. I’m really looking forward to using the new webtrees.

**Comment by fisharebest** [comment]
Thanks.

There is a process in webtrees for cleaning old files from previous versions.  There should be an alert on the control panel telling you if there are any files that could not be deleted automatically.

So can you remove the suggestion about deleting old files?  Also, "all files and directories **except the `data` directory**" includes things that should not be deleted.  Local files in /public (e.g. images from HTML blocks), robots.txt, .htaccess, modules, etc.  There could also be people who have (for historic reasons) stored their media in /media instead of /data/media.

A full description of which files to delete would run to several paragraphs - and you'll still find someone who stores something their MySQL backups or some other important file in root folder.

If you could remove that and update the numbering, that would be great.

 - I know that MarkDown ignores the numbering and auto-fixes it for you, but it upsets my OCD ;-)

> but I'd like to follow-up with some template updates later.

That sounds great.  Maybe you create an issue in the tracker?

**Comment by fisharebest** [comment]
PS - I plan to create an update for the 1.7 branch which checks all the pre-requisites, updates config.ini.php, etc.

Users will then be able to auto upgrade from the latest version of 1.7 to 2.0 automatically.

**Comment by jchue** [comment]
Updated according to your feedback. And totally understand- I'm the same way, but I must've added more steps after my initial pass and missed the numbering.

**Pull request merged**
